<?php

namespace Database\Seeders;

use App\Models\Plan;
use App\Models\PlanFeature;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PlanFeatureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $basic = Plan::where('name', 'Basic')->first();
        $professional = Plan::where('name', 'Professional')->first();
        $professionalPlus = Plan::where('name', 'Professional Plus')->first();

        PlanFeature::insert([
            [
                'plan_id' => $basic->id,
                'ability_to_create_an_account' => 1,
                'ability_to_choose_a_payment_option' => 1,
                'ability_to_share_sensitive_information' => 1,
                'ability_to_work_in_french_or_english' => 1,
                'ability_to_turn_on_or_off_ai' => 1,
                'ability_to_practice_sound_from_word_to_convert_in_english' => 1,
                'ability_to_practice_sound_from_word_to_convert_in_french' => 1,
                'ability_to_practice_any_blend_in_english' => 1,
                'ability_to_practice_any_blend_in_french' => 1,
                'ability_to_choose_any_number_of_syllables_in_english' => 1,
                'ability_to_choose_any_number_of_syllables_in_french' => 1,
                'ability_to_work_on_vowels_from_word_to_convert_in_english' => 0,
                'ability_to_work_on_vowels_from_word_to_convert_in_french' => 0,
                'ability_to_work_on_phonological_processes_to_convert_english' => 0,
                'ability_to_work_on_phonological_processes_to_convert_french' => 0,
                'ability_to_work_on_1_2_sounds_together' => 1,
                'ability_to_work_on_multiple_sounds_together' => 0,
                'ability_to_match_cards_or_items' => 1,
                'ability_to_customize_word_lists_based_on_chosen_sounds' => 1,
                'ability_to_turn_on_prompts' => 1,
                'ability_to_have_multiple_types_of_cueing' => 1,
                'access_to_limited_demonstration_videos' => 1,
                'ability_to_view_activity_progress' => 1,
                'ability_to_view_in_game_progress' => 1,
                'ability_to_level_up' => 1,
                'ability_to_store_results_for_activities' => 0,
                'ability_for_the_phoneme_to_highlight_in_the_word' => 1,
                'ability_to_store_results_for_games_2_weeks' => 1,
                'ability_to_store_results_for_games_for_2_months' => 0,
                'ability_to_store_results_and_of_completion_for_a_world' => 0,
                'ability_to_complete_a_speech_screening' => 1,
                'ability_to_choose_any_world' => 1,
                'ability_to_work_in_groups_up_to_8_people' => 0,
                'ability_to_choose_any_game' => 0,
                'ability_to_choose_any_activity' => 1,
                'ability_to_choose_a_character' => 1,
                'ability_to_earn_coins_or_figures_based_on_personal_perform' => 0,
                'ability_to_purchase_virtual_currency' => 0,
                'possibly_the_ability_to_buy_bonus_world_access' => 1,
                'ability_to_connect_to_clinician_or_learner' => 0,
                'ability_to_share_results_with_clinician_or_guardian' => 0,
                'ability_to_receive_clinician_feedback' => 0,
                'ability_to_customize_character' => 1,
                'ability_to_receive_monthly_reports' => 0,
                'ability_to_find_a_friend_in_the_game' => 0,
                'ability_to_share_an_encrypted_invitation_to_a_clinician' => 0,
                'ability_to_share_an_encrypted_invitation' => 0,
                'ability_to_sign_up_for_an_account_with_a_clinicians_referral' => 0,
                'ability_to_share_the_app_with_family_members' => 1,
                'ability_to_have_2_learner_profiles' => 1,
                'ability_to_interact_with_25_users_during_play' => 0,
                'ability_to_manage_profiles_through_the_app' => 0,
                'ability_to_manage_profiles_through_the_app_up_to' => "0",
                'ability_to_invite_user_to_homework_helper' => 0,
                'ability_to_assign_a_recommended_sound_as_homework' => 0,
                'ability_to_communicate_with_parents_about_results' => 0,
                'ability_to_assign_a_recommended_activity_or_game' => 0,
                'ability_to_view_activity_progress_or_results_per_invite' => 0,
                'ability_to_view_avg_time_used_per_learner' => 0,
                'ability_to_learners_at_each_level' => 0,
                'ability_to_see_the_number_of_learners_that_leveled_up' => 0,
                'ability_to_see_mastered_sounds' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'plan_id' => $professional->id,
                'ability_to_create_an_account' => 1,
                'ability_to_choose_a_payment_option' => 1,
                'ability_to_share_sensitive_information' => 1,
                'ability_to_work_in_french_or_english' => 1,
                'ability_to_turn_on_or_off_ai' => 1,
                'ability_to_practice_sound_from_word_to_convert_in_english' => 1,
                'ability_to_practice_sound_from_word_to_convert_in_french' => 1,
                'ability_to_practice_any_blend_in_english' => 1,
                'ability_to_practice_any_blend_in_french' => 1,
                'ability_to_choose_any_number_of_syllables_in_english' => 1,
                'ability_to_choose_any_number_of_syllables_in_french' => 1,
                'ability_to_work_on_vowels_from_word_to_convert_in_english' => 1,
                'ability_to_work_on_vowels_from_word_to_convert_in_french' => 1,
                'ability_to_work_on_phonological_processes_to_convert_english' => 1,
                'ability_to_work_on_phonological_processes_to_convert_french' => 1,
                'ability_to_work_on_1_2_sounds_together' => 1,
                'ability_to_work_on_multiple_sounds_together' => 1,
                'ability_to_match_cards_or_items' => 1,
                'ability_to_customize_word_lists_based_on_chosen_sounds' => 1,
                'ability_to_turn_on_prompts' => 1,
                'ability_to_have_multiple_types_of_cueing' => 1,
                'access_to_limited_demonstration_videos' => 1,
                'ability_to_view_activity_progress' => 1,
                'ability_to_view_in_game_progress' => 1,
                'ability_to_level_up' => 1,
                'ability_to_store_results_for_activities' => 1,
                'ability_for_the_phoneme_to_highlight_in_the_word' => 1,
                'ability_to_store_results_for_games_2_weeks' => 1,
                'ability_to_store_results_for_games_for_2_months' => 1,
                'ability_to_store_results_and_of_completion_for_a_world' => 1,
                'ability_to_complete_a_speech_screening' => 1,
                'ability_to_choose_any_world' => 1,
                'ability_to_work_in_groups_up_to_8_people' => 0,
                'ability_to_choose_any_game' => 1,
                'ability_to_choose_any_activity' => 1,
                'ability_to_choose_a_character' => 1,
                'ability_to_earn_coins_or_figures_based_on_personal_perform' => 1,
                'ability_to_purchase_virtual_currency' => 1,
                'possibly_the_ability_to_buy_bonus_world_access' => 1,
                'ability_to_connect_to_clinician_or_learner' => 0,
                'ability_to_share_results_with_clinician_or_guardian' => 0,
                'ability_to_receive_clinician_feedback' => 0,
                'ability_to_customize_character' => 1,
                'ability_to_receive_monthly_reports' => 1,
                'ability_to_find_a_friend_in_the_game' => 0,
                'ability_to_share_an_encrypted_invitation_to_a_clinician' => 1,
                'ability_to_share_an_encrypted_invitation' => 1,
                'ability_to_sign_up_for_an_account_with_a_clinicians_referral' => 1,
                'ability_to_share_the_app_with_family_members' => 1,
                'ability_to_have_2_learner_profiles' => 1,
                'ability_to_interact_with_25_users_during_play' => 0,
                'ability_to_manage_profiles_through_the_app' => 1,
                'ability_to_manage_profiles_through_the_app_up_to' => "10",
                'ability_to_invite_user_to_homework_helper' => 1,
                'ability_to_assign_a_recommended_sound_as_homework' => 0,
                'ability_to_communicate_with_parents_about_results' => 0,
                'ability_to_assign_a_recommended_activity_or_game' => 0,
                'ability_to_view_activity_progress_or_results_per_invite' => 0,
                'ability_to_view_avg_time_used_per_learner' => 0,
                'ability_to_learners_at_each_level' => 0,
                'ability_to_see_the_number_of_learners_that_leveled_up' => 0,
                'ability_to_see_mastered_sounds' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'plan_id' => $professionalPlus->id,
                'ability_to_create_an_account' => 1,
                'ability_to_choose_a_payment_option' => 1,
                'ability_to_share_sensitive_information' => 1,
                'ability_to_work_in_french_or_english' => 1,
                'ability_to_turn_on_or_off_ai' => 1,
                'ability_to_practice_sound_from_word_to_convert_in_english' => 1,
                'ability_to_practice_sound_from_word_to_convert_in_french' => 1,
                'ability_to_practice_any_blend_in_english' => 1,
                'ability_to_practice_any_blend_in_french' => 1,
                'ability_to_choose_any_number_of_syllables_in_english' => 1,
                'ability_to_choose_any_number_of_syllables_in_french' => 1,
                'ability_to_work_on_vowels_from_word_to_convert_in_english' => 1,
                'ability_to_work_on_vowels_from_word_to_convert_in_french' => 1,
                'ability_to_work_on_phonological_processes_to_convert_english' => 1,
                'ability_to_work_on_phonological_processes_to_convert_french' => 1,
                'ability_to_work_on_1_2_sounds_together' => 1,
                'ability_to_work_on_multiple_sounds_together' => 1,
                'ability_to_match_cards_or_items' => 1,
                'ability_to_customize_word_lists_based_on_chosen_sounds' => 1,
                'ability_to_turn_on_prompts' => 1,
                'ability_to_have_multiple_types_of_cueing' => 1,
                'access_to_limited_demonstration_videos' => 1,
                'ability_to_view_activity_progress' => 1,
                'ability_to_view_in_game_progress' => 1,
                'ability_to_level_up' => 1,
                'ability_to_store_results_for_activities' => 1,
                'ability_for_the_phoneme_to_highlight_in_the_word' => 1,
                'ability_to_store_results_for_games_2_weeks' => 1,
                'ability_to_store_results_for_games_for_2_months' => 1,
                'ability_to_store_results_and_of_completion_for_a_world' => 1,
                'ability_to_complete_a_speech_screening' => 1,
                'ability_to_choose_any_world' => 1,
                'ability_to_work_in_groups_up_to_8_people' => 1,
                'ability_to_choose_any_game' => 1,
                'ability_to_choose_any_activity' => 1,
                'ability_to_choose_a_character' => 1,
                'ability_to_earn_coins_or_figures_based_on_personal_perform' => 1,
                'ability_to_purchase_virtual_currency' => 1,
                'possibly_the_ability_to_buy_bonus_world_access' => 1,
                'ability_to_connect_to_clinician_or_learner' => 1,
                'ability_to_share_results_with_clinician_or_guardian' => 1,
                'ability_to_receive_clinician_feedback' => 1,
                'ability_to_customize_character' => 1,
                'ability_to_receive_monthly_reports' => 1,
                'ability_to_find_a_friend_in_the_game' => 1,
                'ability_to_share_an_encrypted_invitation_to_a_clinician' => 1,
                'ability_to_share_an_encrypted_invitation' => 1,
                'ability_to_sign_up_for_an_account_with_a_clinicians_referral' => 1,
                'ability_to_share_the_app_with_family_members' => 1,
                'ability_to_have_2_learner_profiles' => 1,
                'ability_to_interact_with_25_users_during_play' => 1,
                'ability_to_manage_profiles_through_the_app' => 1,
                'ability_to_manage_profiles_through_the_app_up_to' => "unlimited",
                'ability_to_invite_user_to_homework_helper' => 1,
                'ability_to_assign_a_recommended_sound_as_homework' => 1,
                'ability_to_communicate_with_parents_about_results' => 1,
                'ability_to_assign_a_recommended_activity_or_game' => 1,
                'ability_to_view_activity_progress_or_results_per_invite' => 1,
                'ability_to_view_avg_time_used_per_learner' => 1,
                'ability_to_learners_at_each_level' => 1,
                'ability_to_see_the_number_of_learners_that_leveled_up' => 1,
                'ability_to_see_mastered_sounds' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
